In [1]:
import pandas as pd 
import numpy as np

In [3]:
# Load dataset
data = pd.read_csv("..\\dataset\\ebay_laptop_data_phase3.csv")
data

,Brand,Price,Color,GPU,Processor Speed,Display Width,Display Height,OS,Storage Type,Hard Drive Capacity,SSD Capacity,Screen Size (cm),Ram Size,Price per Screen Size,Price per Display Height,Price per Display Width,Bluetooth,Touchscreen,WiFi,Webcam
0,dell,400.00,black,intel,4.200000,1920.000000,1080.000000,windows,ssd,2000.00,205.95,14.000000,5.98,28.571429,0.370370,0.208333,Yes,No,Yes,Yes
1,dell,175.00,black,intel,2.400000,1920.000000,1080.000000,windows,ssd,500.00,500.00,14.000000,16.00,12.500000,0.162037,0.091146,Yes,Yes,Yes,Yes
2,hp,85.00,black,intel,2.400000,1366.000000,768.000000,chrome,emmc,16.00,205.95,11.600000,4.00,7.327586,0.110677,0.062225,Yes,No,Yes,Yes
3,dell,101.25,other,other,1.400000,1366.000000,768.000000,windows,ssd,98.89,256.00,12.500000,8.00,8.100000,0.131836,0.074122,No,No,Yes,Yes
4,acer,50.00,black,other,1.600000,1366.000000,768.000000,chrome,ssd,98.89,16.00,11.600000,4.00,4.310345,0.065104,0.036603,Yes,Yes,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2466,dell,429.00,black,intel,2.600000,1280.000000,720.000000,windows,unknown,98.89,960.00,14.000000,5.98,30.642857,0.595833,0.335156,No,No,Yes,No
2467,acer,93.25,other,other,1.186174,779.242171,447.949319,unknown,unknown,98.89,205.95,9.076586,5.98,10.273686,0.208171,0.119668,No,No,No,No
2468,dell,424.80,black,intel,2.800000,1920.000000,1080.000000,windows,unknown,98.89,120.00,12.500000,5.98,33.984000,0.393333,0.221250,Yes,Yes,Yes,Yes
2469,hp,90.94,other,other,1.186174,779.242171,447.949319,unknown,unknown,98.89,205.95,9.076586,5.98,10.019185,0.203014,0.116703,No,No,No,No
2470,lenovo,567.50,black,other,1.186174,779.242171,447.949319,unknown,unknown,98.89,205.95,9.076586,5.98,62.523507,1.266884,0.728272,No,No,No,No

In [12]:
feature = data[["Brand"]]
# feature["Brand_encoded"] = 
num_uniques = feature["Brand"].nunique()
feature_vals = feature["Brand"].unique()
code_list = [i + 1 for i in range(num_uniques)]

encoding_dict = {}
for value, code in zip(feature_vals, code_list):
    encoding_dict[value] = code 

feature["Encoding_brand"] = feature["Brand"].map(encoding_dict)
feature

C:\Users\mian_\AppData\Local\Temp\ipykernel_25740\2751466822.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  feature["Encoding_brand"] = feature["Brand"].map(encoding_dict)

       Brand  Encoding_brand
0       dell               1
1       dell               1
2         hp               2
3       dell               1
4       acer               3
...      ...             ...
2466    dell               1
2467    acer               3
2468    dell               1
2469      hp               2
2470  lenovo               4

[2471 rows x 2 columns]

In [26]:
feature_name = data[["Brand"]].columns.tolist()
feature_name

['Brand']

In [31]:
class LabelEncoder:
    def transform(feature: pd.DataFrame) -> pd.DataFrame: 
        # Define constants
        feature_name = feature_name.columns.tolist()
        num_uniques = feature[feature_name].nunique()
        feature_vals = feature[feature_name].unique()
        code_list = [i + 1 for i in range(num_uniques)]

        # Create encoding dictionary 
        encoding_dict = {}
        for value, code in zip(feature_vals, code_list):
            encoding_dict[value] = code 

        # map the feature value with its encoding value
        encoded_feature = feature["Brand"].map(encoding_dict)
        return encoded_feature

In [32]:
label_encoder = LabelEncoder()
label_encoder.transform(data[["Brand"]])

TypeError: LabelEncoder.transform() takes 1 positional argument but 2 were given